# Generated by Django 3.2.3 on 2021-05-26 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secteur', '0002_alter_secteur_nomsecteur'),
        ('SousSecteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soussecteur',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Secteur.secteur'),
        ),
    ]
