# Generated by Django 3.2.3 on 2021-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=100, null=True)),
                ('ninea', models.CharField(max_length=100, null=True)),
                ('formeJudidique', models.CharField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('telephone', models.IntegerField(max_length=50, null=True)),
                ('siteInternet', models.URLField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('capitalSocial', models.FloatField(null=True)),
                ('chiffreAffaire', models.FloatField(null=True)),
                ('effectif', models.IntegerField(null=True)),
                ('directeurGeneral', models.CharField(max_length=100, null=True)),
                ('activite', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
