# Generated by Django 3.2.3 on 2021-05-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SousSecteur', '0002_soussecteur_secteur'),
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='souSecteur',
            field=models.ManyToManyField(to='SousSecteur.SousSecteur'),
        ),
    ]
