# Generated by Django 3.2.3 on 2021-05-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0002_entreprise_sousecteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='formeJudidique',
            new_name='formeJuridique',
        ),
    ]
