# Generated by Django 3.2.3 on 2021-06-10 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SousSecteur', '0002_soussecteur_secteur'),
        ('Entreprise', '0003_rename_formejudidique_entreprise_formejuridique'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreSecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise')),
                ('sousecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SousSecteur.soussecteur')),
            ],
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='souSecteur',
            field=models.ManyToManyField(null=True, through='Entreprise.EntreSecteur', to='SousSecteur.SousSecteur'),
        ),
    ]
