# Generated by Django 3.2.3 on 2021-06-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SousSecteur', '0002_soussecteur_secteur'),
        ('Entreprise', '0004_auto_20210610_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='souSecteur',
            field=models.ManyToManyField(through='Entreprise.EntreSecteur', to='SousSecteur.SousSecteur'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entresecteur',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entreprise.entreprise'),
        ),
        migrations.AlterField(
            model_name='entresecteur',
            name='sousecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SousSecteur.soussecteur'),
        ),
    ]
