# Generated by Django 3.2.3 on 2021-06-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='loin',
            new_name='login',
        ),
    ]
