# Generated by Django 3.2.3 on 2021-06-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_rename_loin_utilisateur_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
