# Generated by Django 3.2.3 on 2021-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSecteur', models.CharField(choices=[('Commerce', 'Commerce'), ('Industrie', 'Industrie'), ('Industrie', 'Industrie')], max_length=100, null=True)),
            ],
        ),
    ]
