# Generated by Django 3.2.3 on 2021-05-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteur',
            name='nomSecteur',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Industrie', 'Industrie'), ('Service', 'Service')], max_length=100, null=True),
        ),
    ]
